name: Linting Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install htmlhint stylelint

    - name: Run HTMLHint
      run: npx htmlhint "src/**/*.html"

    - name: Run Stylelint
      run: npx stylelint "styles/**/*.css"
