name: Linting Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Grant execution permissions
        run: chmod +x ./node_modules/.bin/stylelint

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"


      
